version: '3.8'
volumes:
  grafana:
  prometheus:
services:
  prometheus:
    image: prom/prometheus
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus:/prometheus
    ports:
      - 9090:9090
    container_name: prometheus
  grafana:
    image: grafana/grafana
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning/datasources
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    container_name: grafana
    depends_on:
      - prometheus
  node-app:
    build: ./app/
    image: node-app
    ports:
      - 3030:3030
    container_name: node-app
    depends_on:
      - prometheus
      - grafana

  
    
